@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor TrafficManager
participant TopPairsUI as UI
participant TopPairsController as Controller
participant ":Company" as Company
participant "store :ShipStore" as Store

activate TrafficManager
TrafficManager -> UI: asks for the Ship pairs
activate UI
UI -> Controller: getPairs()
activate Controller
Controller -> Company: store = getShipStore()
activate Company
deactivate
Controller -> Store: getPairsOfShipsString()
activate Store
Store -> Store: getPairOfShipsInsideBST()
activate Store
deactivate Store
return
return

UI --> TrafficManager: returns the ship pairs
deactivate UI



deactivate TrafficManager
@enduml