@startuml
actor TrafficManager
participant System

activate TrafficManager
TrafficManager -> System: asks for the Ship pairs
activate System
System --> TrafficManager: returns the ship pairs
deactivate System



deactivate TrafficManager
@enduml