ALTER TABLE Employee ADD PRIMARY KEY (name, Roleid);
ALTER TABLE "Employee/Facility" ADD PRIMARY KEY (Employeename, Facilityid, EmployeeRoleid);
ALTER TABLE "Employee/Ship" ADD PRIMARY KEY (Employeename, EmployeeRoleid, Shipmmsi, ShipTransportid);
ALTER TABLE Client ADD PRIMARY KEY (id);
ALTER TABLE Ship ADD PRIMARY KEY (mmsi, Transportid);
ALTER TABLE Container ADD PRIMARY KEY (containerID);
ALTER TABLE Truck ADD PRIMARY KEY (Transporterid);
ALTER TABLE PositionalMessage ADD PRIMARY KEY (baseDateTime, Shipmmsi, ShipTransportid);
ALTER TABLE "Truck/Employee" ADD PRIMARY KEY (Employeename, EmployeeRoleid, TruckTransportid2);
ALTER TABLE ContainerPosition ADD PRIMARY KEY (ContainercontainerID);
ALTER TABLE ISOCode ADD PRIMARY KEY (id);
ALTER TABLE Role ADD PRIMARY KEY (id);
ALTER TABLE Port ADD PRIMARY KEY (Facilityid);
ALTER TABLE Warehouse ADD PRIMARY KEY (Facilityid);
ALTER TABLE Continent ADD PRIMARY KEY (id);
ALTER TABLE Country ADD PRIMARY KEY (id);
ALTER TABLE "Container / Client" ADD PRIMARY KEY (Clientid, ContainercontainerID);
ALTER TABLE Facility ADD PRIMARY KEY (id);
ALTER TABLE Transporter ADD PRIMARY KEY (id);
ALTER TABLE CargoManifest ADD PRIMARY KEY (id, Transporertid);
ALTER TABLE "CargoManifest Container" ADD PRIMARY KEY (ContainercontainerID, CargoManifestid, CargoManifestTransportid);
ALTER TABLE "Facility / Truck" ADD PRIMARY KEY (baseDateTime, Facilityid, TruckTransportid);
ALTER TABLE "Facility / Ship" ADD PRIMARY KEY (baseDateTime, Facilityid, Shipmmsi, ShipTransportid);
