@startuml
'https://plantuml.com/class-diagram


class GetAuditTrailUI{
+run()
}
class GetAuditTrailController{
+GetAuditTrailController()
+getAuditTrail()
}
class GetAuditTrailScript{
getAuditTrail(DatabaseConnection databaseConnection)
}

GetAuditTrailUI ..> GetAuditTrailController
GetAuditTrailController .> GetAuditTrailScript
@enduml