@startuml

actor "Port Manager" as ACT

participant "System" as SYS

activate ACT
ACT -> SYS : starts process
activate SYS
SYS -> ACT : requests facility ID
deactivate SYS

ACT -> SYS : inputs facility ID
activate SYS
SYS -> ACT : prints out result
deactivate SYS
deactivate ACT



@enduml
