@startuml

class FindAvailableShipsUI{
  +run()
}

class FindAvailableShipsController{
  +getAvailableShips()
}

class ShipStore{
  +getShipByCallsign()
}

class Ship{

}

class Company{
  +getShipStore()
}

FindAvailableShipsUI ..> FindAvailableShipsController
FindAvailableShipsController -> Company
Company -> ShipStore
ShipStore -> Ship

@enduml
