@startuml

actor "Traffic Manager" as ACT
participant System as SYS

activate ACT
ACT -> SYS : starts process
activate SYS
SYS -> ACT : returns all available ships on next week's monday
deactivate System
deactivate ACT

@enduml
